database:
  url = jdbc:h2:mem:PUBLIC;DB_CLOSE_DELAY=-1
  login = sa
  password =
  migration.location = db/migration
  driver = org.h2.Driver
hibernate:
  hbm2ddl.auto.property = "create-drop"
  dialect.property = org.hibernate.dialect.H2Dialect
  show_sql.property = true
  format_sql.property = true

  entity.package.to.scan = com.itrex.java.lab.persistence.entity